using System.Text.Json;
using System.Text.Json.Serialization;
using ProwlersAndParagonsAutomation.Tools.RulebookExtractor;
using UglyToad.PdfPig;

// Regenerates data/rulebook/ from the publisher's PDF.
//
//   dotnet run --project tools/RulebookExtractor -- <path-to-pdf> <output-dir>
//
// The PDF is gitignored and lives in the main working directory's docs/, never in a worktree's.
// Nothing in the app runs this; the corpus it writes is committed and the tests read that.

if (args.Length < 2)
{
    Console.Error.WriteLine("usage: RulebookExtractor <rulebook.pdf> <output-dir>");
    return 2;
}

var (pdfPath, outputDir) = (args[0], args[1]);

// The printed page number plus this is the PDF page. Constant across the book, verified at both
// ends: printed 13 is PDF 16 and printed 188 is PDF 191. Declared here, ahead of both diagnostic
// modes below, because both need it too.
const int PageOffset = 3;

// `--page <printed>` prints that page's lines in the order the reader puts them, marking each
// heading. Diagnosing a scrambled section from the finished JSON is guesswork; this is not.
if (args is [_, _, "--page", _, ..])
{
    using var one = PdfDocument.Open(pdfPath);
    var printedPage = int.Parse(args[3]);
    foreach (var l in new PageReader().Read(one.GetPage(printedPage + PageOffset)))
        Console.WriteLine($"{(l.IsHeading ? "H" : " ")} [{l.Baseline,6:F0} {l.Left,6:F1}-{l.Right,6:F1} sz{l.Size,5:F1}] {l.Text}");
    return 0;
}

// `--gaps <from> <to>` prints one CSV row per non-heading line that has a known predecessor in
// its own column-run — printed page, font size, the gap from the line above it, and the line's
// own text — for every page in the printed range. This is how the paragraph-break threshold
// below was chosen: run it over the whole book and look at the distribution, not by eye on one
// page. Restricted to body-sized text because a run against a heading's own larger size would
// mix two different leadings into one histogram.
if (args is [_, _, "--gaps", _, _, ..])
{
    using var two = PdfDocument.Open(pdfPath);
    var from = int.Parse(args[3]);
    var to = int.Parse(args[4]);
    Console.WriteLine("page,size,gap,text");
    for (var printed = from; printed <= to; printed++)
    {
        var pdfPage = printed + PageOffset;
        if (pdfPage < 1 || pdfPage > two.NumberOfPages) continue;
        foreach (var l in new PageReader().Read(two.GetPage(pdfPage)))
        {
            if (l.IsHeading || l.LeadingGap is null) continue;
            var gap = l.LeadingGap.Value;
            var snippet = l.Text.Length > 30 ? l.Text[..30] : l.Text;
            Console.WriteLine($"{printed},{l.Size:F1},{gap:F2},\"{snippet}\"");
        }
    }
    return 0;
}

if (!File.Exists(pdfPath)) { Console.Error.WriteLine($"no such PDF: {pdfPath}"); return 2; }
Directory.CreateDirectory(outputDir);

// Printed page ranges, from the table of contents. Chapter 9's text ends on printed 188; printed
// 189 is the blank Hero Sheet form, which is a form and not prose — extracted, it yielded
// eighteen sections of field labels with no text under them, so it is deliberately excluded.
Chapter[] chapters =
[
    new(0, "Introduction",           "ch00-introduction.json",          5,   8),
    new(1, "Basics",                 "ch01-basics.json",                9,  12),
    new(2, "Characters",             "ch02-characters.json",           13,  65),
    new(3, "Action",                 "ch03-action.json",               67,  72),
    new(4, "Combat",                 "ch04-combat.json",               73,  82),
    new(5, "Resolve and Adversity",  "ch05-resolve-and-adversity.json",83,  86),
    new(6, "Equipment",              "ch06-equipment.json",            87, 104),
    new(7, "Environment",            "ch07-environment.json",         105, 110),
    new(8, "Friends and Foes",       "ch08-friends-and-foes.json",    111, 166),
    new(9, "Superhero Gaming",       "ch09-superhero-gaming.json",    167, 188)
];

const string ExtractionNote =
    "Generated by tools/RulebookExtractor from the publisher's PDF; do not hand-edit, it is "
  + "overwritten on the next run. The gutter is found per page and a line crossing it is kept "
  + "whole, so full-width text — every chapter opening is set that way — is not cut in half. The "
  + "running foot, the purchaser watermark and the rotated chapter title in the margin are "
  + "dropped. Headings are detected by typeface, and a heading with no body of its own qualifies "
  + "the ones beneath it, which is how a character's name reaches their stat block. A section's "
  + "own paragraph breaks are kept as \\n, read off the page's own vertical spacing rather than "
  + "invented from sentence shape. Two known limits: a heading set in small capitals extracts "
  + "with its case as stored rather than as printed (Chapter 8's stat-block labels), and a table "
  + "of three or more columns is read across rather than down — which the paragraph logic also "
  + "splits at row boundaries, without repairing the underlying scramble.";

var reader = new PageReader();
var options = new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
    WriteIndented = true,
    // The book uses curly quotes, bullets and ½ throughout. Without this they serialize as
    // ’ escapes, which makes the corpus unreadable to anyone opening the file.
    Encoder = System.Text.Encodings.Web.JavaScriptEncoder.Create(System.Text.Unicode.UnicodeRanges.All)
};

using var doc = PdfDocument.Open(pdfPath);
var grandTotal = 0;

foreach (var chapter in chapters)
{
    var sections = new List<Section>();

    // The open section runs across page breaks. An entry that begins at the foot of one page and
    // finishes on the next is one entry, and it is cited to the page its heading is printed on —
    // splitting it per page produced several sections sharing a heading, so a reader looking up
    // "PHASING" found the entry in pieces.
    string? heading = null;
    var headingPage = chapter.From;
    var body = new List<PageReader.Line>();

    // A heading immediately followed by another heading has no body of its own, and it is almost
    // always the one that says what the thing IS: a character's code name above "villain", or a
    // table's title above its column headers. Discarding it lost every name in Chapter 8 — all
    // twenty Heroes, all twenty Villains — leaving pages of anonymous "ABILITIES" and "POWERS"
    // with nothing to say whose they were. It is carried instead, and qualifies the headings
    // beneath it until one of its own size or larger appears.
    // Point size is the outline level: a character's code name is set far larger than the
    // "ABILITIES"/"POWERS" labels beneath it. Anything on the stack qualifies what follows, and a
    // heading pops everything at its own level or above before it is used — which is what stops
    // a sibling label inheriting its predecessor's name, and what stops the qualifier growing
    // without bound. A single qualifier slot could not express two levels, and chaining without
    // popping produced one 1,795-character heading listing every character in the chapter.
    var outline = new Stack<(string Text, double Size)>();
    var headingSize = 0.0;

    void PopTo(double size)
    {
        while (outline.Count > 0 && outline.Peek().Size <= size) outline.Pop();
    }

    void Close()
    {
        var text = ParagraphJoiner.Join(body);
        if (heading is not null && text.Length > 0)
        {
            PopTo(headingSize);
            var prefix = string.Join(" — ", outline.Reverse().Select(o => o.Text));
            sections.Add(new Section(
                prefix.Length == 0 ? heading : $"{prefix} — {heading}", headingPage, text));
        }
        body.Clear();
    }

    for (var printed = chapter.From; printed <= chapter.To; printed++)
    {
        var pdfPage = printed + PageOffset;
        if (pdfPage < 1 || pdfPage > doc.NumberOfPages) continue;

        foreach (var line in reader.Read(doc.GetPage(pdfPage)))
        {
            if (line.IsHeading)
            {
                var hadBody = ParagraphJoiner.Join(body).Length > 0;
                Close();

                // A heading that never got a body is the one that says what this IS — a
                // character's code name above "villain", a table's title above its column
                // headers. Discarding those lost every name in Chapter 8: all twenty Heroes and
                // all twenty Villains, leaving pages of anonymous "ABILITIES" and "POWERS".
                if (!hadBody && heading is not null)
                {
                    PopTo(headingSize);
                    outline.Push((heading, headingSize));
                }

                heading = line.Text.Trim();
                headingSize = line.Size;
                headingPage = printed;
            }
            else
            {
                if (heading is null) { heading = "(opening)"; headingPage = printed; headingSize = 0; }
                body.Add(line);
            }
        }
    }

    Close();

    var file = Path.Combine(outputDir, chapter.File);
    var payload = new ChapterFile(
        chapter.Number,
        chapter.Title,
        [chapter.From, chapter.To],
        $"Ultimate Edition, Ch.{chapter.Number} {chapter.Title}, pp.{chapter.From}-{chapter.To}",
        ExtractionNote,
        sections);

    File.WriteAllText(file, JsonSerializer.Serialize(payload, options) + "\n");
    Console.WriteLine($"{chapter.File,-34} pp.{chapter.From}-{chapter.To,-4} {sections.Count,4} sections");
    grandTotal += sections.Count;
}

Console.WriteLine($"{"total",-34}                {grandTotal,4} sections");
return 0;

internal sealed record Chapter(int Number, string Title, string File, int From, int To);

internal sealed record ChapterFile(
    [property: JsonPropertyName("chapter")] int Number,
    string Title,
    int[] PrintedPages,
    string SourceRef,
    string Extraction,
    IReadOnlyList<Section> Sections);

internal sealed record Section(string Heading, int PrintedPage, string Text);
