#!/usr/bin/env bash
#
# Writes the Cloudflare Pages `_headers` file into a published site.
#
# The Content-Security-Policy is why this is a script and not a static file. Blazor emits
# an inline <script type="importmap"> into index.html naming the fingerprinted framework
# assets, so its contents change whenever those are rebuilt. Under `script-src 'self'` an
# inline script is blocked and the app never boots; allowing 'unsafe-inline' instead would
# give up most of what the policy is for. So the hash is taken from the index.html that
# was actually published.
#
# One implementation, run by the deploy workflow and by anyone checking the policy
# locally — a second copy is somewhere for the two to disagree.
#
# Usage: scripts/write-cloudflare-headers.sh <published-wwwroot>

set -euo pipefail

root="${1:?usage: write-cloudflare-headers.sh <published-wwwroot>}"
index="$root/index.html"

[ -f "$index" ] || { echo "error: no index.html under $root" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# Split out the body of every inline <script> — one file each, byte for byte, because
# that is what the hash has to cover. Scripts with a src attribute are external and are
# already allowed by 'self'. Hashing whatever inline scripts exist, rather than the
# import map by name, means a framework version that adds another one stays covered.
awk -v dir="$work" '
    BEGIN { n = 0; inside = 0; buf = "" }
    {
        line = $0
        while (length(line) > 0 || inside) {
            if (!inside) {
                if (!match(line, /<script[^>]*>/)) break
                tag  = substr(line, RSTART, RLENGTH)
                line = substr(line, RSTART + RLENGTH)
                if (tag ~ /src[ \t]*=/) continue
                inside = 1; buf = ""
                continue
            }

            close_at = index(line, "</script>")
            if (close_at > 0) {
                buf = buf substr(line, 1, close_at - 1)
                n++
                printf "%s", buf > (dir "/" n)
                close(dir "/" n)
                line = substr(line, close_at + 9)
                inside = 0
                continue
            }

            buf = buf line "\n"
            break
        }
    }
    END { if (inside) { print "error: unclosed <script> in index.html" > "/dev/stderr"; exit 1 } }
' "$index"

hashes=""
count=0
for body in "$work"/*; do
    [ -e "$body" ] || break
    digest=$(openssl dgst -sha256 -binary < "$body" | base64)
    hashes="$hashes 'sha256-$digest'"
    count=$((count + 1))
done

if [ "$count" -eq 0 ]; then
    echo "error: found no inline scripts in index.html." >&2
    echo "Blazor emits an import map there; finding none means the parser or the" >&2
    echo "framework's output has changed, and shipping the policy anyway would" >&2
    echo "produce a site that silently fails to boot." >&2
    exit 1
fi

cat > "$root/_headers" <<HEADERS
# Generated by scripts/write-cloudflare-headers.sh — do not edit by hand. The script
# hashes the inline scripts of the index.html that was actually published, and those
# change whenever the framework assets are re-fingerprinted.

/*
  Content-Security-Policy: default-src 'self'; script-src 'self'${hashes} 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), publickey-credentials-get=(), screen-wake-lock=(), usb=(), xr-spatial-tracking=()

# Fingerprinted assets are immutable by construction — the name changes when the bytes do
# — so they can be cached hard. index.html must not be, or a deploy would never reach
# anyone still holding the old one.
/_framework/*
  Cache-Control: public, max-age=31536000, immutable

# Both spellings. Cloudflare matches _headers rules against the requested path, not the
# file it resolves to, so a rule for /index.html does not cover "/" — which is the URL
# almost everyone actually asks for. Left alone, the front page falls back to the
# platform default and the rule reads as though it were doing something it is not.
/index.html
  Cache-Control: no-cache

/
  Cache-Control: no-cache

# The rules data is not fingerprinted and is what the engine runs on, so a stale copy is a
# wrong rulebook rather than a cosmetic problem. Revalidate every time.
/data/rules/*
  Cache-Control: no-cache
HEADERS

echo "Wrote $root/_headers with $count inline script hash(es):$hashes"
