namespace ProwlersAndParagonsAutomation.Tests;

/// <summary>
/// The Range, Rank and Cost printed for every Power in Prowlers &amp; Paragons Ultimate
/// Edition, Chapter 2 (pp.21-48), transcribed from the rulebook. This is the reference
/// powers.json is checked against, so a data edit that contradicts the book fails a test
/// rather than silently mispricing characters.
///
/// <para><c>Printed</c> is the stat line as it appears in the book, kept so an entry can be
/// eyeballed against the page named in <c>Page</c>. <c>CostSpec</c> is the same cost in a
/// compact form the test rebuilds from <see cref="Engine.Models.PowerModel"/>.</para>
/// </summary>
public static class CanonicalPowers
{
    public sealed record Entry(
        string Id,
        string Range,
        string RankType,
        string CostSpec,
        int Page,
        string Printed);

    public static readonly IReadOnlyList<Entry> All =
    [
        new("adaptation", "self", "default", "flat=12", 21, "Self - Default Rank - 12 Hero Points"),
        new("alternate_form", "self", "default", "per_unit=4/power level", 21, "Self - Default Rank - 4 Hero Points per power level"),
        new("animal_control", "ranged", "power", "per_rank=1", 21, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("animal_empathy", "self", "default", "flat=1", 22, "Self - Default Rank - 1 Hero Point"),
        new("animal_mimicry", "self", "power", "per_rank=2", 22, "Self - Power Rank - 2 Hero Points per rank"),
        new("animation", "ranged", "power", "per_rank=2", 22, "Ranged - Power Rank - 2 Hero Points per rank"),
        new("armor", "self", "baseline", "per_rank=1", 22, "Self - Baseline Rank (½ Toughness) - 1 Hero Point per rank"),
        new("astral_projection", "self", "default", "flat=12", 23, "Self - Default Rank - 12 Hero Points"),
        new("attuned", "self", "default", "flat=3", 23, "Self - Default Rank - 3 Hero Points"),
        new("aura", "self", "power", "per_rank=2", 23, "Self - Power Rank - 2 Hero Points per rank"),
        new("banish", "ranged", "power", "per_rank=1", 23, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("blast", "ranged", "power", "per_rank=1", 24, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("blending", "self", "default", "flat=3", 24, "Self - Default Rank - 3 Hero Points"),
        new("blind", "ranged", "power", "per_rank=0.5", 24, "Ranged - Power Rank - 1 Hero Point per 2 ranks"),
        new("blind_fighting", "self", "default", "flat=3", 24, "Self - Default Rank - 3 Hero Points"),
        new("blink", "self", "power", "per_rank=1", 24, "Self - Power Rank - 1 Hero Point per rank"),
        new("boost", "self", "baseline", "special", 24, "Self - Baseline Rank (Special) - Special"),
        new("buff", "zone", "default", "flat=12", 25, "Zone - Default Rank - 12 Hero Points"),
        new("clairvoyance", "self", "default", "flat=9", 25, "Self - Default Rank - 9 Hero Points"),
        new("cloud_minds", "ranged", "power", "per_rank=1", 25, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("communications", "self", "default", "flat=3", 25, "Self - Default Rank - 3 Hero Points"),
        new("constructs", "ranged", "power", "per_rank=3", 25, "Ranged - Power Rank - 3 Hero Points per rank"),
        new("danger_sense", "self", "baseline", "per_rank=1", 25, "Self - Baseline Rank (Perception) - 1 Hero Point per rank"),
        new("darkness", "zone", "default", "flat=6", 25, "Zone - Default Rank - 6 Hero Points"),
        new("dazzle", "zone", "power", "per_rank=1", 26, "Zone - Power Rank - 1 Hero Point per rank"),
        new("deflection", "self", "power", "per_rank=1", 26, "Self - Power Rank - 1 Hero Point per rank"),
        new("density", "self", "power", "per_rank=1", 26, "Self - Power Rank - 1 Hero Point per rank"),
        new("detection", "ranged", "power", "per_rank=0.5", 26, "Ranged - Power Rank - 1 Hero Point per 2 ranks"),
        new("determination", "self", "special", "per_unit=5/resolve", 26, "Self - Special - 5 Hero Points per 1 Resolve"),
        new("dimensional_travel", "self", "default", "flat=6", 26, "Self - Default Rank - 6 Hero Points"),
        new("dispel", "ranged", "power", "per_rank=0.5", 26, "Ranged - Power Rank - 1 Hero Point per 2 ranks"),
        new("drain", "ranged", "power", "per_rank=0.5", 27, "Ranged - Power Rank - 1 Hero Point per 2 ranks"),
        new("duplication", "self", "default", "flat=25", 27, "Self - Default Rank - 25 Hero Points"),
        new("elemental_control", "ranged", "power", "per_rank=3", 27, "Ranged - Power Rank - 3 Hero Points per rank"),
        new("emotion_control", "ranged", "power", "per_rank=1", 28, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("energy_absorption", "self", "power", "per_rank_variable=kinetic:3,standard:1", 28, "Self - Power Rank - 1 or 3 Hero Points per rank"),
        new("ensnare", "ranged", "power", "per_rank=1", 28, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("evasion", "self", "baseline", "per_rank=0.5", 28, "Self - Baseline Rank (Agility) - 1 Hero Point per 2 ranks"),
        new("expertise", "self", "baseline", "per_rank=0.5", 28, "Self - Baseline Rank (Special) - 1 Hero Point per 2 ranks"),
        new("extra_limbs", "self", "default", "flat=3", 28, "Self - Default Rank - 3 Hero Points"),
        new("flight", "self", "power", "per_rank=1", 29, "Self - Power Rank - 1 Hero Point per rank"),
        new("force_field", "self", "power", "per_rank=1", 29, "Self - Power Rank - 1 Hero Point per rank"),
        new("form_energy", "self", "power", "per_rank=3", 30, "Self - Power Rank - 3 Hero Points per rank"),
        new("form_gaseous", "self", "default", "flat=6", 30, "Self - Default Rank - 6 Hero Points"),
        new("form_liquid", "self", "default", "flat=12", 30, "Self - Default Rank - 12 Hero Points"),
        new("form_solid", "self", "power", "per_rank=2", 30, "Self - Power Rank - 2 Hero Points per rank"),
        new("gestalt", "self", "default", "flat=3", 30, "Self - Default Rank - 3 Hero Points"),
        new("growth", "self", "power", "per_rank=1", 30, "Self - Power Rank - 1 Hero Point per rank"),
        new("hard_to_kill", "self", "default", "flat=1", 30, "Self - Default Rank - 1 Hero Point"),
        new("healing", "touch", "power", "per_rank=1", 31, "Touch - Power Rank - 1 Hero Point per rank"),
        new("hibernation", "self", "default", "flat=1", 31, "Self - Default Rank - 1 Hero Point"),
        new("hyper_breath", "special", "power", "per_rank=1", 31, "Special - Power Rank - 1 Hero Point per rank"),
        new("illusions", "zone", "power", "per_rank=1", 31, "Zone - Power Rank - 1 Hero Point per rank"),
        new("immortality", "self", "default", "flat=3", 31, "Self - Default Rank - 3 Hero Points"),
        new("immunity", "self", "default", "per_unit=3/immunity", 31, "Self - Default Rank - 3 Hero Points per immunity"),
        new("inanimate", "self", "special", "flat=9", 32, "Self - Special - 9 Hero Points"),
        new("invisibility", "self", "default", "flat=9", 32, "Self - Default Rank - 9 Hero Points"),
        new("irritant", "zone", "power", "per_rank=1", 32, "Zone - Power Rank - 1 Hero Point per rank"),
        new("languages", "self", "default", "flat=1", 32, "Self - Default Rank - 1 Hero Point"),
        new("leadership", "self", "default", "flat=6", 32, "Self - Default Rank - 6 Hero Points"),
        new("leaping", "self", "baseline", "per_rank=1", 32, "Self - Baseline Rank (½ Might) - 1 Hero Point per rank"),
        new("life_drain", "touch", "power", "per_rank=2", 33, "Touch - Power Rank - 2 Hero Points per rank"),
        new("light_effect", "special", "default", "flat=3", 33, "Special - Default Rank - 3 Hero Points"),
        new("lightning_reflexes", "self", "default", "flat=3", 33, "Self - Default Rank - 3 Hero Points"),
        new("luck", "self", "power", "per_rank=2", 33, "Self - Power Rank - 2 Hero Points per rank"),
        new("machine_control", "ranged", "power", "per_rank=1", 33, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("martial_arts", "touch", "baseline", "per_rank=1", 34, "Touch - Baseline Rank (Might) - 1 Hero Point per rank"),
        new("master_of_disguise", "self", "default", "flat=3", 34, "Self - Default Rank - 3 Hero Points"),
        new("matter_chameleon", "self", "power", "per_rank=2", 35, "Self - Power Rank - 2 Hero Points per rank"),
        new("mind_blast", "ranged", "power", "per_rank=1", 35, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("mind_control", "ranged", "power", "per_rank=2", 35, "Ranged - Power Rank - 2 Hero Points per rank"),
        new("nullify", "zone", "power", "per_rank=2", 35, "Zone - Power Rank - 2 Hero Points per rank"),
        new("omni_power", "special", "power", "per_rank_variable=broad:5,narrow:3", 35, "Special - Power Rank - 3 or 5 Hero Points per rank"),
        new("phasing", "self", "default", "flat=9", 36, "Self - Default Rank - 9 Hero Points"),
        new("plasticity", "self", "power", "per_rank=2", 36, "Self - Power Rank - 2 Hero Points per rank"),
        new("polymorph", "ranged", "power", "per_rank=1", 36, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("portable_storehouse", "self", "default", "flat=6", 36, "Self - Default Rank - 6 Hero Points"),
        new("possession", "ranged", "power", "per_rank=1", 36, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("power_absorption", "touch", "power", "per_rank=2", 37, "Touch - Power Rank - 2 Hero Points per rank"),
        new("precognition", "self", "default", "flat=12", 37, "Self - Default Rank - 12 Hero Points"),
        new("power_mimicry", "touch", "power", "per_rank=2", 37, "Touch - Power Rank - 2 Hero Points per rank"),
        new("preparation", "self", "special", "flat=6", 38, "Self - Special - 6 Hero Points"),
        new("psi_screen", "self", "baseline", "per_rank=1", 38, "Self - Baseline Rank (Willpower) - 1 Hero Point per rank"),
        new("psychometry", "touch", "default", "flat=9", 38, "Touch - Default Rank - 9 Hero Points"),
        new("quick_change", "self", "default", "flat=3", 38, "Self - Default Rank - 3 Hero Points"),
        new("radar", "self", "default", "flat=3", 38, "Self - Default Rank - 3 Hero Points"),
        new("regeneration", "self", "default", "flat=6", 38, "Self - Default Rank - 6 Hero Points"),
        new("resistance", "self", "baseline", "per_rank=0.5", 39, "Self - Baseline Rank (Toughness) - 1 Hero Point per 2 ranks"),
        new("running", "self", "baseline", "per_rank=1", 39, "Self - Baseline Rank (3d) - 1 Hero Point per rank"),
        new("separation", "self", "default", "flat=3", 39, "Self - Default Rank - 3 Hero Points"),
        new("shockwave", "zone", "power", "per_rank=0.5", 39, "Zone - Power Rank - 1 Hero Point per 2 ranks"),
        new("shrinking", "self", "power", "per_rank=2", 39, "Self - Power Rank - 2 Hero Points per rank"),
        new("slay", "touch", "power", "per_rank=2", 39, "Touch - Power Rank - 2 Hero Points per rank"),
        new("slick", "zone", "power", "per_rank=1", 39, "Zone - Power Rank - 1 Hero Point per rank"),
        new("speak_with_dead", "self", "power", "per_rank=2", 39, "Self - Power Rank - 2 Hero Points per rank"),
        new("specialty", "self", "special", "flat=0", 40, "Self - Special - 0 Hero Points"),
        new("spinning", "self", "power", "per_rank=1", 40, "Self - Power Rank - 1 Hero Point per rank"),
        new("star_gate", "self", "default", "flat=3", 41, "Self - Default Rank - 3 Hero Points"),
        new("stretching", "self", "default", "flat_variable=close_range:1,distant_range:3,extreme_range:6", 41, "Self - Default Rank - 1, 3 or 6 Hero Points"),
        new("strike", "touch", "baseline", "per_rank=1", 41, "Touch - Baseline Rank (Might) or (Martial Arts) - 1 Hero Point per rank"),
        new("stun", "ranged", "power", "per_rank=1", 42, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("summoning", "self", "power", "special", 42, "Self - Power Rank - Special"),
        new("super_senses_acute", "self", "baseline", "per_rank=0.5", 43, "Self - Baseline Rank (Perception) - 1 Hero Point per 2 ranks"),
        new("super_senses_analytic", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_astral_sight", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_circular_vision", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_enhanced_hearing", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_hypersensitive_touch", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_lie_detection", "self", "baseline", "flat=3", 43, "Self - Baseline Rank (Perception) - 3 Hero Points"),
        new("super_senses_microscopic_vision", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_night_vision", "self", "baseline", "flat=3", 43, "Self - Baseline Rank (Perception) - 3 Hero Points"),
        new("super_senses_radio_hearing", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_telescopic_vision", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_thermal_vision", "self", "baseline", "flat=2", 43, "Self - Baseline Rank (Perception) - 2 Hero Points"),
        new("super_senses_tracking_scent", "self", "baseline", "flat=1", 43, "Self - Baseline Rank (Perception) - 1 Hero Point"),
        new("super_senses_true_sight", "self", "baseline", "flat=6", 43, "Self - Baseline Rank (Perception) - 6 Hero Points"),
        new("super_senses_ultra_vision", "self", "baseline", "flat=2", 43, "Self - Baseline Rank (Perception) - 2 Hero Points"),
        new("super_senses_x_ray_vision", "self", "baseline", "flat=6", 43, "Self - Baseline Rank (Perception) - 6 Hero Points"),
        new("super_speed", "self", "power", "per_rank=3", 44, "Self - Power Rank - 3 Hero Points per rank"),
        new("swimming", "self", "power", "per_rank=0.5", 44, "Self - Power Rank - 1 Hero Point per 2 ranks"),
        new("swing_line", "self", "power", "per_rank=0.5", 44, "Self - Power Rank - 1 Hero Point per 2 ranks"),
        new("telekinesis", "ranged", "power", "per_rank=2", 44, "Ranged - Power Rank - 2 Hero Points per rank"),
        new("telepathy", "ranged", "power", "per_rank=1", 45, "Ranged - Power Rank - 1 Hero Point per rank"),
        new("teleportation", "self", "power", "per_rank=1", 45, "Self - Power Rank - 1 Hero Point per rank"),
        new("time_stop", "zone", "power", "per_rank=3", 45, "Zone - Power Rank - 3 Hero Points per rank"),
        new("time_travel", "self", "default", "flat=3", 46, "Self - Default Rank - 3 Hero Points"),
        new("total_recall", "self", "default", "flat=3", 46, "Self - Default Rank - 3 Hero Points"),
        new("tracer", "touch", "default", "flat=3", 46, "Touch - Default Rank - 3 Hero Points"),
        new("transformation_animal_forms", "self", "power", "per_rank=2", 46, "Self - Power Rank - 2 Hero Points per rank"),
        new("transformation_doppelganger", "self", "default", "flat=6", 46, "Self - Default Rank - 6 Hero Points"),
        new("transformation_object_forms", "self", "power", "per_rank=2", 46, "Self - Power Rank - 2 Hero Points per rank"),
        new("transformation_shapeshifting", "self", "power", "per_rank=2", 46, "Self - Power Rank - 2 Hero Points per rank"),
        new("transmutation", "touch", "power", "per_rank=2", 47, "Touch - Power Rank - 2 Hero Points per rank"),
        new("vanish", "self", "default", "flat=3", 47, "Self - Default Rank - 3 Hero Points"),
        new("tunneling", "self", "power", "per_rank=1", 47, "Self - Power Rank - 1 Hero Point per rank"),
        new("two_dimensional", "self", "default", "flat=6", 47, "Self - Default Rank - 6 Hero Points"),
        new("two_fisted", "self", "default", "flat=3", 47, "Self - Default Rank - 3 Hero Points"),
        new("variant", "special", "special", "flat=3", 48, "Special - Special - 3 Hero Points"),
        new("ventriloquism", "self", "default", "flat=3", 48, "Self - Default Rank - 3 Hero Points"),
        new("wall_crawling", "self", "power", "per_rank=0.5", 48, "Self - Power Rank - 1 Hero Point per 2 ranks"),
        new("weakness_detection", "self", "default", "flat=3", 48, "Self - Default Rank - 3 Hero Points"),
    ];
}
