namespace ProwlersAndParagonsAutomation.Tests;

/// <summary>
/// Every Pro and Con the rulebook attaches to one named Power rather than to Powers in
/// general, with the Hero Point change it gives. These are distinct from the generic Pros
/// and Cons in pros.json / cons.json, and unlike those, several change the Power's cost
/// per rank rather than its total.
///
/// <para>Almost all are printed inside the Power's own entry in Chapter 2. Three are not:
/// Caustic, Lethal Disease and Non-Lethal Disease sit in Chapter 7's Toxins section (p.108)
/// and name Stun or Slay in their text. Sweeping the whole book for a PRO/CON Hero Point
/// marker returns those three and nothing else outside Chapter 2.</para>
///
/// <para>Transcribed from the rulebook. If a test using this fails, check the page in the
/// Power's <c>source_ref</c> — do not edit this table to match the code.</para>
/// </summary>
public static class CanonicalPowerProsCons
{
    public sealed record Entry(string PowerId, string Kind, string Id, string CostSpec);

    public static readonly IReadOnlyList<Entry> All =
    [
        new("alternate_form", "con", "independent_forms", "per_unit=-1/power level"),
        new("animal_control", "pro", "calling", "flat=2"),
        new("animal_control", "con", "only_x", "flat_variable=narrow:-4,standard:-2"),
        new("animal_empathy", "pro", "speech", "flat=2"),
        new("animal_mimicry", "pro", "enhanced", "flat=4"),
        new("animal_mimicry", "pro", "selection", "flat=4"),
        new("armor", "con", "activated", "flat=-1"),
        new("armor", "con", "reactive", "flat=-2"),
        new("aura", "con", "spines", "flat=-2"),
        new("blast", "pro", "block", "flat=2"),
        new("blast", "pro", "melee", "flat=2"),
        new("blast", "con", "subdual", "flat=-1"),
        new("blast", "con", "weapons", "flat=-1"),
        new("boost", "con", "rage", "flat=-2"),
        new("buff", "pro", "greater", "flat=6"),
        new("constructs", "pro", "devices", "per_rank=2"),
        new("dazzle", "con", "deafen", "flat=-1"),
        new("deflection", "con", "only_x", "flat=-4"),
        new("detection", "pro", "long_range", "flat=1"),
        new("dimensional_travel", "pro", "portal", "flat=2"),
        new("dispel", "pro", "also_x", "per_rank_per_unit=0.5/additional Source"),
        new("drain", "pro", "also_x", "per_rank_per_unit=0.5/additional Source"),
        new("drain", "con", "only_x", "flat_variable=narrow:-4,standard:-2"),
        new("elemental_control", "pro", "matter_creation", "per_rank=1"),
        new("elemental_control", "con", "only_control", "per_rank=-1"),
        new("emotion_control", "con", "only_x", "flat=-2"),
        new("emotion_control", "con", "pheromones", "flat=-2"),
        new("energy_absorption", "pro", "also_x", "flat=2"),
        new("ensnare", "pro", "line", "flat=2"),
        new("ensnare", "con", "immobilize", "flat=-2"),
        new("flight", "pro", "spaceflight", "flat=2"),
        new("flight", "con", "gliding", "flat=-2"),
        new("flight", "con", "levitation", "flat=-4"),
        new("flight", "con", "slides", "flat=-2"),
        new("flight", "con", "wings", "flat=-2"),
        new("force_field", "pro", "inviolate", "per_rank=1"),
        new("force_field", "pro", "permeable", "flat=6"),
        new("force_field", "con", "collapsible", "flat=-2"),
        new("force_field", "con", "ward", "flat=-1"),
        new("form_energy", "pro", "also_x", "flat=2"),
        new("healing", "con", "repair", "flat=-2"),
        new("hyper_breath", "pro", "freezing", "per_rank=1"),
        new("illusions", "pro", "mental", "per_rank=2"),
        new("immortality", "con", "vulnerable", "flat=-1"),
        new("inanimate", "pro", "mindless", "flat=9"),
        new("invisibility", "pro", "cloaking", "flat=3"),
        new("invisibility", "con", "jamming", "flat=-3"),
        new("languages", "pro", "hyper_translation", "flat=2"),
        new("languages", "pro", "polyglot", "flat=1"),
        new("life_drain", "pro", "vampirism", "flat=1"),
        new("lightning_reflexes", "con", "fighting_marksmanship", "flat=-1"),
        new("luck", "pro", "control", "flat=4"),
        new("luck", "pro", "unbelievable", "per_rank=1"),
        new("machine_control", "con", "interface", "flat=-2"),
        new("martial_arts", "pro", "deflect", "flat=4"),
        new("martial_arts", "pro", "deflect_missiles", "flat=2"),
        new("mind_control", "con", "hypnosis", "flat=-2"),
        new("mind_control", "con", "pheromones", "flat=-2"),
        new("nullify", "pro", "also_x", "per_rank_per_unit=1/additional Source"),
        new("phasing", "pro", "intangible", "flat=3"),
        new("possession", "pro", "meld", "flat=4"),
        new("power_absorption", "pro", "also_x", "per_rank_per_unit=1/additional Source"),
        new("power_absorption", "con", "only_x", "flat_variable=narrow:-4,standard:-2"),
        new("power_mimicry", "pro", "also_x", "per_rank_per_unit=1/additional Source"),
        new("power_mimicry", "con", "only_x", "flat_variable=narrow:-4,standard:-2"),
        new("psi_screen", "pro", "cloak_mind", "flat=2"),
        new("quick_change", "con", "costume", "flat=-1"),
        new("radar", "con", "sonar", "flat=-1"),
        new("radar", "con", "tremor_sense", "flat=-1"),
        new("regeneration", "pro", "fast", "flat=6"),
        new("regeneration", "pro", "instant", "flat=18"),
        new("running", "pro", "hover", "flat=2"),
        new("slay", "pro", "lethal_disease", "flat=6"),
        new("star_gate", "pro", "portal", "flat=2"),
        new("stretching", "con", "long_reach", "flat=-1"),
        new("strike", "pro", "deflect", "flat=4"),
        new("strike", "pro", "deflect_missiles", "flat=2"),
        new("strike", "pro", "reach_throw", "flat=2"),
        new("strike", "pro", "sweep", "flat=4"),
        new("strike", "con", "subdual", "flat=-1"),
        new("strike", "con", "weapons", "flat=-1"),
        new("stun", "pro", "non_lethal_disease", "flat=2"),
        new("stun", "con", "caustic", "flat=-2"),
        new("stun", "con", "emp", "flat=-2"),
        new("summoning", "pro", "animals", "per_rank_variable=narrow_selection:1,wide_variety:2"),
        new("summoning", "pro", "automatons", "per_rank=1"),
        new("summoning", "pro", "duplicates", "per_rank=2"),
        new("summoning", "pro", "shooters", "per_rank=1"),
        new("summoning", "pro", "unique", "per_rank_variable=minor:1,moderate:2,major:4"),
        new("swimming", "con", "lungs", "flat=-1"),
        new("swing_line", "con", "natural", "flat=-2"),
        new("telekinesis", "con", "impel", "flat=-4"),
        new("telepathy", "pro", "alter_memories", "flat=6"),
        new("telepathy", "pro", "cloak_others", "flat=2"),
        new("telepathy", "pro", "dream_travel", "flat=2"),
        new("telepathy", "pro", "mind_link", "flat=2"),
        new("telepathy", "con", "empathy", "flat=-2"),
        new("teleportation", "pro", "portal", "flat=2"),
        new("teleportation", "con", "medium", "flat=-2"),
        new("time_travel", "pro", "portal", "flat=2"),
        new("total_recall", "pro", "playback", "flat=1"),
        new("tracer", "pro", "tracking", "flat=3"),
        new("transformation_animal_forms", "pro", "enhanced", "flat=4"),
        new("transformation_animal_forms", "con", "only_x", "flat_variable=narrow:-4,standard:-2"),
        new("transmutation", "con", "fighting_marksmanship", "flat=-1"),
    ];
}
